<a href="https://colab.research.google.com/github/marianoq/data_science/blob/main/Pr%C3%A1ctica_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Librería Numpy**

In [ ]:
import numpy as np

In [ ]:
# Array de una dimensión
array_unidim = np.array([1,2,3,4,5])

# Array de dos dimensiones
array_bidim = np.array([[1,2,3],
                        [4,5,6]])

# Array de tres dimensiones
array_tridim = np.array([[[1,2,3],
                          [2,3,4]],
                         [[7,8,9],
                          [10,11,12]]])

In [ ]:
# Obtener atributos del Array unidimencional (forma,nro de dim,tipo de datos, tamaño, tipo)
array_unidim.shape, array_unidim.ndim, array_unidim.dtype, array_unidim.size, type(array_unidim)

((5,), 1, dtype('int64'), 5, numpy.ndarray)

In [ ]:
# Obtener atributos del Array bidimencional (forma,nro de dim,tipo de datos, tamaño, tipo)
array_bidim.shape, array_bidim.ndim, array_bidim.dtype, array_bidim.size, type(array_bidim)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [ ]:
# Obtener atributos del Array tridimencional (forma,nro de dim,tipo de datos, tamaño, tipo)
array_tridim.shape, array_tridim.ndim, array_tridim.dtype, array_tridim.size, type(array_tridim)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [ ]:
import pandas as pd

datos = pd.DataFrame(array_bidim)
datos

0  1  2
0  1  2  3
1  4  5  6

In [ ]:
# Crear un array de 4x3 de unos
unos = np.ones((4,3))
unos

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Crear un array de 2x4x3, formado por ceros
ceros = np.zeros((2,4,3))
ceros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# Crear un array de nros del 0 al 100, con paso de 5
array_1 = np.arange(0,101,5)
array_1

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [ ]:
# Crear un array de nros aleatorios enteros comprendidos entre 0 y 10 de tamaño 2x3
array_2 = np.random.randint(0,10,(2,5))
array_2

array([[5, 1, 8, 2, 4],
       [9, 8, 3, 4, 7]])

In [ ]:
# Crear un array de nros aleatorios decimales comprendidos entre 0 y 1 de tamaño 3x5
array_2 = np.random.random((3,5))
array_2

array([[0.51682371, 0.41475647, 0.64858625, 0.76848115, 0.13556537],
       [0.83958284, 0.54498776, 0.12088124, 0.40987321, 0.24204134],
       [0.65422005, 0.04473069, 0.25589855, 0.43770199, 0.32684   ]])

In [ ]:
# Establecer semilla de numero aleatorio
np.random.seed(2)
# Crear un array de nros aleatorios enteros comprendidos entre 0 y 10 de tamaño 3x5
array_3 = np.random.randint(0,10,(3,5))
array_3

array([[8, 8, 6, 2, 8],
       [7, 2, 1, 5, 4],
       [4, 5, 7, 3, 6]])

In [ ]:
# Crear un array de nros aleatorios enteros comprendidos entre 0 y 10 de tamaño 3x5
array_4 = np.random.randint(0,10,(3,5))
array_4

array([[4, 3, 7, 6, 1],
       [3, 5, 8, 4, 6],
       [3, 9, 2, 0, 4]])

In [ ]:
# Valores únicos
np.unique(array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Extraer el elemento del indice 1
array_4[1]

array([3, 5, 8, 4, 6])

In [ ]:
# Extraer las dos primeras filas
array_4[:2]

array([[4, 3, 7, 6, 1],
       [3, 5, 8, 4, 6]])

In [ ]:
# Extraer los dos primeros datos de las dos filas
array_4[:2,:2]

array([[4, 3],
       [3, 5]])

In [ ]:
#  Creamos dos arrays de tamaño 3x4: uno relleno de números aleatorios entre 0 y 10, y otro relleno de unos
array_5 = np.random.randint(0,11,(3,4))
array_6 = np.ones((3,4))

In [ ]:
# Array 5
array_5

array([[ 6,  8, 10,  5],
       [ 9,  9,  9, 10],
       [ 3,  0,  0, 10]])

In [ ]:
# Array 6
array_6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# Sumar los dos array 5 + 6
array_5 + array_6

array([[ 7.,  9., 11.,  6.],
       [10., 10., 10., 11.],
       [ 4.,  1.,  1., 11.]])

In [ ]:
# Crear array de unos de 4x3
array_7 = np.ones((4,3))
array_7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Sumo el 6 + 7
array_6 + array_7

ValueError: ignored

In [ ]:
# Crear otro array de unos de 4x3
array_8 = np.ones((4,3))
array_8

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Restar array 8 - array 7
array_8 - array_7

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# Crear dos array de 3x3 con nros aleatorios del 1 al 5
array_9 = np.random.randint(1,5,(3,3))
array_10 = np.random.randint(1,5,(3,3))

In [ ]:
# Array 9
array_9

array([[3, 1, 1],
       [3, 3, 1],
       [3, 1, 2]])

In [ ]:
# Array 10
array_10

array([[3, 2, 3],
       [3, 3, 4],
       [1, 3, 2]])

In [ ]:
# Multriplicar el 9 por el 10
array_9 * array_10

array([[9, 2, 3],
       [9, 9, 4],
       [3, 3, 4]])

In [ ]:
# Elevar el 9 al cuadrado
array_9 ** 2

array([[9, 1, 1],
       [9, 9, 1],
       [9, 1, 4]])

In [ ]:
# Raiz cuadrada del 10
np.sqrt(array_10)

array([[1.73205081, 1.41421356, 1.73205081],
       [1.73205081, 1.73205081, 2.        ],
       [1.        , 1.73205081, 1.41421356]])

In [ ]:
# Promedio de valores del 9
array_9.mean()

2.0

In [ ]:
# Valor max del 9
array_9.max()

3

In [ ]:
# Valor minimo del 9
array_9.min()

1

In [ ]:
# Cambiar la forma del array 9 por uno de 9x1 y almacenarlo en uno nuevo
array_11 = array_9.reshape(9,1)

In [ ]:
# Array 11
array_11

array([[3],
       [1],
       [1],
       [3],
       [3],
       [1],
       [3],
       [1],
       [2]])

In [ ]:
# Trasponer array 11
array_11.T

array([[3, 1, 1, 3, 3, 1, 3, 1, 2]])

In [ ]:
# Comparar array 9 y array 10 para saber cúales elementos del array 9 son mayores al array 10
array_12 = array_9 > array_10
array_12

array([[False, False, False],
       [False, False, False],
       [ True, False, False]])

In [ ]:
# Tipo de valores
array_12.dtype

dtype('bool')

In [ ]:
# Ver si algún tipo de valor del array 9 es igual su equivalente del array 10
array_9 == array_10

array([[ True, False, False],
       [ True,  True, False],
       [False, False,  True]])

In [ ]:
# Buscar elementos en el array_9 que son > a 2
array_9 > 2

array([[ True, False, False],
       [ True,  True, False],
       [ True, False, False]])

In [ ]:
#  Ordenar valores dentro del array de men a may
np.sort(array_9)

array([[1, 1, 3],
       [1, 3, 3],
       [1, 2, 3]])